USE [master]
GO
/****** Object:  Database [Test_ProductDB]    Script Date: 21/12/2023 9:56:08 p. m. ******/
CREATE DATABASE [Test_ProductDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Test_ProductDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Test_ProductDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Test_ProductDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Test_ProductDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Test_ProductDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Test_ProductDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Test_ProductDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Test_ProductDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Test_ProductDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Test_ProductDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Test_ProductDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [Test_ProductDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Test_ProductDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Test_ProductDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Test_ProductDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Test_ProductDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Test_ProductDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Test_ProductDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Test_ProductDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Test_ProductDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Test_ProductDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Test_ProductDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Test_ProductDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Test_ProductDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Test_ProductDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Test_ProductDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Test_ProductDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Test_ProductDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Test_ProductDB] SET RECOVERY FULL 
GO
ALTER DATABASE [Test_ProductDB] SET  MULTI_USER 
GO
ALTER DATABASE [Test_ProductDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Test_ProductDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Test_ProductDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Test_ProductDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Test_ProductDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Test_ProductDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Test_ProductDB', N'ON'
GO
ALTER DATABASE [Test_ProductDB] SET QUERY_STORE = OFF
GO
USE [Test_ProductDB]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 21/12/2023 9:56:08 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Description] [varchar](50) NULL,
	[Stock] [int] NULL,
	[Price] [float] NULL,
	[CreateBy] [varchar](50) NULL,
	[CreatedDate] [datetime] NULL,
	[UpdateBy] [varchar](50) NULL,
	[UpdatedDate] [datetime] NULL,
	[Status] [bit] NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Test_ProductDB] SET  READ_WRITE 
GO
